[dev]
  command = "npm run dev"

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
