[dev]
  command = "npm run dev"

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/images/*.!(svg)"  # Aplica a todas as imagens, exceto SVG
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
    Expires = "Thu, 25 Sep 2025 00:00:00 GMT"
